name: ci

on:
  pull_request:
  push:
    branches:
      - dev
      - main

env:
  CARGO_INCREMENTAL: 0
  # do not set RUSTFLAGES, would overrides .cargo/config (linker script, flip-link)

jobs:
  build-lpc55:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
    steps:
      - uses: actions/checkout@v1
      - name: Install littlefs2-sys/micro-ecc-sys build dependencies
        shell: bash
        run: |
          env && pwd && sudo apt-get update -y -qq && sudo apt-get install -y -qq llvm libc6-dev-i386 libclang-dev clang
      - uses: fiam/arm-none-eabi-gcc@v1
        with:
          release: "9-2020-q2"
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: thumbv8m.main-none-eabi
          override: true
          components: llvm-tools-preview
      # Use precompiled binutils
      - name: cargo install cargo-binutils
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-binutils
          version: latest
          use-tool-cache: true
      - name: cargo install flip-link
        uses: actions-rs/install@v0.1
        with:
          crate: flip-link
          version: latest
          use-tool-cache: true
      - name: Build firmware
        run: |
          git clone https://github.com/solokeys/solo2 && cd solo2/runners/lpc55
          cargo build --release --features board-solo2
          cargo size --release --features board-solo2
      - name: Upload
        uses: actions/upload-artifact@v2
        continue-on-error: true
        with:
          name: Firmware
          path: solo2/runners/lpc55/target/thumbv8m.main-none-eabi/release/runner

  run-lpc55:
    needs: build-lpc55
    runs-on: self-hosted
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: Firmware
          path: firmware.elf
      - name: Install python dependencies
        run: pip3 install -r requirements.txt
      - name: test
        run: |
          ls
          python3 control.py reboot
          ls
